// Builds data/fields/agincourt-1415.yaml: the field of Agincourt, 25 October 1415, on the field
// map at 10 m a hex. Run from this folder after editing: node make_agincourt_field.mjs
// (no packages needed).
//
// Sources, all plain fact, and the drawing is ours: the field lies between the woods of
// Azincourt (west) and Tramecourt (east), on the road north from Maisoncelle, where the
// English camped; the gap between the woods narrows towards the English end. The woods' edges
// here are drawn by hand to that shape, not traced from any map, and are approximate. The
// deployment is the outline most modern accounts agree on, put in our own words: the English
// in one line of three small "battles" of dismounted men-at-arms with archers between them and
// on the wings, stakes in front of the archers; the French in three lines, the first two of
// dismounted men-at-arms, with mounted wings to ride down the archers and a mounted rear.
// Numbers are disputed; those here are round figures for play.
import { N, S, wobble, lerp, groundGrid, unit, firstCol, writeField } from "./field_lib.mjs";

const COLS = 100, ROWS = 80;                  // 1000 m east to west, about 690 m north to south
const westEdge = r => Math.round(lerp(4, 12, r / (ROWS - 1)) + wobble(r, 0.7, 2.1));    // Azincourt wood: cols below this
const eastEdge = r => Math.round(lerp(94, 87, r / (ROWS - 1)) + wobble(r, 3.9, 1.3));   // Tramecourt wood: cols above this
const grid = groundGrid(COLS, ROWS, (c, r) => (c < westEdge(r) || c > eastEdge(r) ? "F" : "."));
grid.paint(0, 9, 0, 5, "r");       // the edge of Azincourt village, its closes and orchards, to the north-west
grid.paint(96, 99, 34, 42, "r");   // a clearing by Tramecourt, to the east behind the wood

// ---------- the armies (pos is the middle of the front row) ----------
const EN = { side: 0, facing: N }, FR = { side: 1, facing: S };
const ARCHERS = { quality: "veteran", weapon: "longbow", kit: "gambeson", formation: "open", mounted: false };
const MEN_AT_ARMS = { quality: "veteran", weapon: "poleaxe", kit: "full_plate", formation: "close", mounted: false };
const KNIGHTS = { ...MEN_AT_ARMS, quality: "regular" };
const MOUNTED = { quality: "veteran", weapon: "spear", kit: "full_plate", formation: "close", mounted: true };
const MOUNTED_REAR = { ...MOUNTED, quality: "regular" };
const FRONT_EN = 66, FRONT_FR = 42;
const units = [
  unit("Archers, left wing", EN, 1600, ARCHERS, [16, 12, FRONT_EN]),
  unit("Rearward (Camoys)", EN, 320, MEN_AT_ARMS, [8, 28, FRONT_EN]),
  unit("Archers, left wedge", EN, 900, ARCHERS, [9, 36, FRONT_EN]),
  unit("Main battle (the King)", EN, 320, MEN_AT_ARMS, [8, 45, FRONT_EN]),
  unit("Archers, right wedge", EN, 900, ARCHERS, [9, 53, FRONT_EN]),
  unit("Vaward (York)", EN, 320, MEN_AT_ARMS, [8, 62, FRONT_EN]),
  unit("Archers, right wing", EN, 1600, ARCHERS, [16, 70, FRONT_EN]),
  unit("Mounted wing, west", FR, 800, MOUNTED, [10, 9, FRONT_FR]),
  unit("Vanguard", FR, 4800, MEN_AT_ARMS, [60, 20, FRONT_FR]),
  unit("Mounted wing, east", FR, 800, MOUNTED, [10, 81, FRONT_FR]),
  unit("Main battle", FR, 4800, KNIGHTS, [60, 20, 30]),
  unit("Rearguard (mounted)", FR, 3000, MOUNTED_REAR, [75, 12, 16]),
];
// Stakes: a row in front of each body of archers, one hex ahead of their front.
const stakes = units.filter(u => u.weapon === "longbow").flatMap(u => Array.from({ length: u.width }, (_, i) => [firstCol(u) + i, FRONT_EN - 1]));

writeField({
  id: "agincourt-1415", name: "Agincourt, 25 October 1415", sides: ["English", "French"], table: "towton-1461-all-hits",
  travel: { map: "agincourt-1415", place: "Azincourt", within: 1, sides: ["England", "France"] },
  weather: "{cond: overcast, wind: calm, ground: {mud: 3, snow: 0}}",
  grid, hexWorks: { stakes }, units,
  header: [
    `The field of Agincourt, 25 October 1415 (Julian), at 10 m a hex: ${COLS} x ${ROWS} hexes, about 1000 m`,
    "east to west and 690 m north to south, north at the top.",
    "Generated by tools/maps/make_agincourt_field.mjs: edit that file and re-run it rather than this one.",
    "The woods' edges are drawn by hand to the shape the accounts give (a gap narrowing towards",
    "the English), not traced from any map; the deployment is the outline most modern accounts",
    "share, in our own words, with round numbers for play.",
    "",
    "What happened, briefly: after a night of heavy rain the two armies stood a long way apart on",
    "freshly ploughed, sodden ground. The English moved forward to within long bowshot, planted",
    "their stakes again and shot, provoking the French. The mounted wings charged first, were",
    "stopped by the stakes and arrows, and rode back through their own vanguard; the vanguard",
    "struggled forward through the mud, crowding in towards the English men-at-arms, and was",
    "fought to a standstill and cut down, the archers joining in from the flanks. The main battle",
    "fared little better; most of the rearguard never came on.",
  ],
});
console.log(grid.map(r => r.join("")).join("\n"));
