// Builds data/fields/agincourt-1415.yaml: the field of Agincourt, 25 October 1415, on the field
// map at 10 m a hex. Run from this folder after editing: node make_agincourt_field.mjs
// (no packages needed).
//
// Sources, all plain fact, and the drawing is ours: the field lies between the woods of
// Azincourt (west) and Tramecourt (east), on the road north from Maisoncelle, where the
// English camped; the gap between the woods narrows towards the English end. The woods' edges
// here are drawn by hand to that shape, not traced from any map, and are approximate. The
// deployment is the outline most modern accounts agree on, put in our own words: the English
// in one line of three small "battles" of dismounted men-at-arms with archers between them and
// on the wings, stakes in front of the archers; the French in three lines, the first two of
// dismounted men-at-arms, with mounted wings to ride down the archers and a mounted rear.
// Numbers are disputed; those here are round figures for play.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "../..");
const COLS = 100, ROWS = 80;                  // 1000 m east to west, about 690 m north to south

// A smooth wobble for the wood edges: a sum of sines, fixed so the file is the same each run.
const wobble = (r, a, b) => 1.4 * Math.sin(r / 5.3 + a) + 0.8 * Math.sin(r / 2.1 + b);
const lerp = (a, b, t) => a + (b - a) * t;
const westEdge = r => Math.round(lerp(4, 12, r / (ROWS - 1)) + wobble(r, 0.7, 2.1));    // Azincourt wood: cols below this
const eastEdge = r => Math.round(lerp(94, 87, r / (ROWS - 1)) + wobble(r, 3.9, 1.3));   // Tramecourt wood: cols above this

const grid = Array.from({ length: ROWS }, (_, r) => Array.from({ length: COLS }, (_, c) => (c < westEdge(r) || c > eastEdge(r) ? "F" : ".")));
const paint = (c0, c1, r0, r1, k) => { for (let r = r0; r <= r1; r++) for (let c = c0; c <= c1; c++) grid[r][c] = k };
paint(0, 9, 0, 5, "r");            // the edge of Azincourt village, its closes and orchards, to the north-west
paint(96, 99, 34, 42, "r");        // a clearing by Tramecourt, to the east behind the wood

// ---------- the armies (facing 1 is north, 4 is south; pos is the middle of the front row) ----------
const EN = 0, FR = 1, N = 1, S = 4;
const unit = (name, side, men, quality, weapon, kit, formation, width, col0, row, facing, mounted = false) =>
  ({ name, side, men, quality, weapon, kit, formation, width, pos: [col0 + Math.floor((width - 1) / 2) + (facing === S ? width % 2 === 0 ? 1 : 0 : 0), row], facing, mounted });
const FRONT_EN = 66, FRONT_FR = 42;
const units = [
  unit("Archers, left wing", EN, 1600, "veteran", "longbow", "gambeson", "open", 16, 12, FRONT_EN, N),
  unit("Rearward (Camoys)", EN, 320, "veteran", "poleaxe", "full_plate", "close", 8, 28, FRONT_EN, N),
  unit("Archers, left wedge", EN, 900, "veteran", "longbow", "gambeson", "open", 9, 36, FRONT_EN, N),
  unit("Main battle (the King)", EN, 320, "veteran", "poleaxe", "full_plate", "close", 8, 45, FRONT_EN, N),
  unit("Archers, right wedge", EN, 900, "veteran", "longbow", "gambeson", "open", 9, 53, FRONT_EN, N),
  unit("Vaward (York)", EN, 320, "veteran", "poleaxe", "full_plate", "close", 8, 62, FRONT_EN, N),
  unit("Archers, right wing", EN, 1600, "veteran", "longbow", "gambeson", "open", 16, 70, FRONT_EN, N),
  unit("Mounted wing, west", FR, 800, "veteran", "spear", "full_plate", "close", 10, 9, FRONT_FR, S, true),
  unit("Vanguard", FR, 4800, "veteran", "poleaxe", "full_plate", "close", 60, 20, FRONT_FR, S),
  unit("Mounted wing, east", FR, 800, "veteran", "spear", "full_plate", "close", 10, 81, FRONT_FR, S, true),
  unit("Main battle", FR, 4800, "regular", "poleaxe", "full_plate", "close", 60, 20, 30, S),
  unit("Rearguard (mounted)", FR, 3000, "regular", "spear", "full_plate", "close", 75, 12, 16, S, true),
];
// Stakes: a row in front of each body of archers, one hex ahead of their front.
const stakes = [];
for (const u of units.filter(x => x.weapon === "longbow")){
  const c0 = u.pos[0] - Math.floor((u.width - 1) / 2);
  for (let c = c0; c < c0 + u.width; c++) stakes.push([c, FRONT_EN - 1]);
}

// ---------- the file ----------
const yq = s => JSON.stringify(s);
const unitLine = u => `  - {name: ${yq(u.name)}, side: ${u.side}, men: ${u.men}, quality: ${u.quality}, weapon: ${u.weapon}, kit: ${u.kit}, formation: ${u.formation}, width: ${u.width}, pos: [${u.pos.join(", ")}], facing: ${u.facing}${u.mounted ? ", mounted: true" : ""}}`;
const out = `# The field of Agincourt, 25 October 1415 (Julian), at 10 m a hex: ${COLS} x ${ROWS} hexes, about 1000 m
# east to west and 690 m north to south, north at the top.
# Generated by tools/maps/make_agincourt_field.mjs: edit that file and re-run it rather than this one.
# The woods' edges are drawn by hand to the shape the accounts give (a gap narrowing towards
# the English), not traced from any map; the deployment is the outline most modern accounts
# share, in our own words, with round numbers for play.
#
# What happened, briefly: after a night of heavy rain the two armies stood a long way apart on
# freshly ploughed, sodden ground. The English moved forward to within long bowshot, planted
# their stakes again and shot, provoking the French. The mounted wings charged first, were
# stopped by the stakes and arrows, and rode back through their own vanguard; the vanguard
# struggled forward through the mud, crowding in towards the English men-at-arms, and was
# fought to a standstill and cut down, the archers joining in from the flanks. The main battle
# fared little better; most of the rearguard never came on.
id: agincourt-1415
name: "Agincourt, 25 October 1415"
sides: ["English", "French"]
table: towton-1461-all-hits
size: [${COLS}, ${ROWS}]
weather: {cond: overcast, wind: calm, ground: {mud: 3, snow: 0}}
ground: |
${grid.map(row => "  " + row.join("")).join("\n")}
works:
  hexes:
    - {type: stakes, at: [${stakes.map(h => `[${h.join(", ")}]`).join(", ")}]}
units:
${units.map(unitLine).join("\n")}
`;
fs.mkdirSync(path.join(root, "data/fields"), { recursive: true });
fs.writeFileSync(path.join(root, "data/fields/agincourt-1415.yaml"), out);
console.log(grid.map(r => r.join("")).join("\n"));
