// Builds data/fields/towton-1461.yaml: the field of Towton, Palm Sunday, 29 March 1461, on the
// field map at 10 m a hex. Run from this folder after editing: node make_towton_field.mjs
// (no packages needed).
//
// Sources, all plain fact, and the drawing is ours: the battle was fought on the plateau
// between Saxton (south) and Towton (north). Its west side drops steeply to Cock Beck, with
// Castle Hill Wood on the slope at the north-west; a shallow dale crosses the plateau between
// the two ridges the armies stood on. The edges here are drawn by hand to that shape, not traced
// from any map, and are approximate. The deployment is the outline most modern accounts share,
// in our own words: each army's archers in front of its main body; Lancastrian men hidden in
// Castle Hill Wood; the Duke of Norfolk's men coming up late on the Yorkist right. Numbers are
// disputed; those here are round figures for play.
import { N, S, wobble, groundGrid, unit, writeField } from "./field_lib.mjs";

const COLS = 150, ROWS = 120;                 // 1500 m east to west, about 1040 m north to south
const beck = r => 4 + 0.8 * wobble(r, 0.3, 1.7);              // Cock Beck, down in its valley
const slopeTop = r => 22 + wobble(r, 2.2, 0.4);               // the top of the steep west slope
const northRidge = c => 50 + wobble(c / 2, 1.1, 2.9);         // the Lancastrian ridge: rows above this
const southRidge = c => 71 + wobble(c / 2, 0.5, 1.9);         // the Yorkist ridge: rows below this
function kind(c, r){
  const b = beck(r);
  if (Math.abs(c - b) <= 2) return "m";                     // the beck and its flooded meadow
  if (r <= 34 && c > b + 2 && c < 32 - r * 0.4 + wobble(r, 3.1, 0.2)) return "F";   // Castle Hill Wood
  if (r >= 96 && c > b + 2 && c < 18 + wobble(r, 1.4, 2.6)) return "F";            // Renshaw Wood, towards Saxton
  if (c < slopeTop(r)) return "r";                          // the steep slopes either side of the beck
  if ((r < northRidge(c) && r > 12) || (r > southRidge(c) && r < 108)) return "h";     // the two ridges
  return ".";
}
const grid = groundGrid(COLS, ROWS, kind);

// ---------- the armies (pos is the middle of the front row) ----------
const YORK = { side: 0, facing: N }, LANC = { side: 1, facing: S };
const ARCHERS = { quality: "regular", weapon: "longbow", kit: "jack_sallet", formation: "open", mounted: false };
const BILLS = { quality: "regular", weapon: "bill", kit: "jack_sallet", formation: "close", mounted: false };
const FRONT_Y = 75, FRONT_L = 50;
const units = [
  unit("Archers (Fauconberg)", YORK, 5000, { ...ARCHERS, quality: "veteran" }, [100, 30, FRONT_Y]),
  unit("Edward's battle", YORK, 11000, BILLS, [100, 30, FRONT_Y + 4]),
  unit("Norfolk's men (coming up late)", YORK, 5000, BILLS, [30, 116, 110]),
  unit("Lancastrian archers", LANC, 6000, ARCHERS, [100, 30, FRONT_L]),
  unit("Somerset's battle", LANC, 14000, BILLS, [100, 30, FRONT_L - 4]),
  unit("Rear battle (Exeter, Northumberland)", LANC, 6000, BILLS, [100, 30, FRONT_L - 10]),
  unit("Men in Castle Hill Wood", LANC, 1500, BILLS, [10, 14, 28]),
];

writeField({
  id: "towton-1461", name: "Towton, 29 March 1461", sides: ["Yorkists", "Lancastrians"], table: "towton-1461-all-hits",
  travel: { map: "towton-1461", place: "Towton", within: 3, sides: ["York", "Lancaster"] },
  weather: "{cond: snow, wind: strong, ground: {mud: 0, snow: 1}}",
  grid, units,
  header: [
    `The field of Towton, Palm Sunday, 29 March 1461 (Julian), at 10 m a hex: ${COLS} x ${ROWS} hexes,`,
    "about 1500 m east to west and 1040 m north to south, north at the top.",
    "Generated by tools/maps/make_towton_field.mjs: edit that file and re-run it rather than this one.",
    "The slopes, the beck, the woods and the ridges are drawn by hand to the shape the accounts",
    "give, not traced from any map; the deployment is the outline most modern accounts share, in",
    "our own words, with round numbers for play.",
    "",
    "What happened, briefly: the armies drew up on two ridges across the plateau, the Lancastrians",
    "to the north, in snow driven by a wind from the south into the Lancastrians' faces. The",
    "Yorkist archers shot, stepped back out of reach and shot again with the Lancastrians' own",
    "arrows; the Lancastrians, shooting short and blind, came on. The lines fought for hours, the",
    "Lancastrians gaining ground, helped by men from Castle Hill Wood on the Yorkist left, until",
    "the Duke of Norfolk's men came up on the Yorkist right. The Lancastrian line gave way, and",
    "many were killed in the rout down to Cock Beck and on towards Tadcaster.",
    "The wind's direction is not in the rules: the GM can give the Lancastrian archers a further",
    "penalty, or the Yorkist archers more reach.",
  ],
});
console.log(grid.map(r => r.join("")).join("\n"));
