// Builds data/fields/visby-1361.yaml: the battle outside Visby's walls, 27 July 1361, on the
// field map at 10 m a hex. Run from this folder after editing: node make_visby_field.mjs
// (no packages needed).
//
// Sources, all plain fact, and the drawing is ours: the Gotland levies fought the Danish army
// outside Visby's ring wall, by the south gate and near Solberga nunnery, where the mass graves
// were later found (Korsbetningen); the town kept its gates shut. The wall, the gate, the
// nunnery and the ground here are drawn by hand to that description, not traced from any map,
// and are approximate. The deployment is our own reading, in our own words: the Gotlanders
// with their backs to the wall, the Danes coming up from the south. Numbers are disputed;
// those here are round figures for play.
import { N, S, wobble, groundGrid, unit, writeField } from "./field_lib.mjs";

const COLS = 80, ROWS = 70;                   // 800 m east to west, about 600 m north to south
const WALL_ROW = 4;                           // the town is rows 0 to 4, behind the ring wall
const GATE_COL = 30;                          // the south gate
function kind(c, r){
  if (r <= WALL_ROW) return "r";                                          // the town's streets and yards
  if (c >= 54 && c <= 62 && r >= 7 && r <= 12) return "r";                // Solberga nunnery and its closes
  if (c < 14 + wobble(r, 0.9, 2.2) && r > 38 && r < 50) return "r";      // stony ground
  if (c > 70 + wobble(r, 1.7, 0.5) && r > 44) return "F";               // woods to the south-east
  return ".";
}
const grid = groundGrid(COLS, ROWS, kind);

// The wall along the town's edge: every side between a row-4 hex and the row-5 hexes below it
// (the town side first). On an even row a hex's southern neighbours are (c-1, r+1) and (c, r+1).
const wall = [], gate = [];
for (let c = 0; c < COLS; c++){
  for (const below of [[c - 1, WALL_ROW + 1], [c, WALL_ROW + 1]]){
    if (below[0] < 0) continue;
    (c === GATE_COL && below[0] === c ? gate : wall).push([[c, WALL_ROW], below]);
  }
}

// ---------- the armies (pos is the middle of the front row) ----------
const GOT = { side: 0, facing: S }, DAN = { side: 1, facing: N };
const LEVY = { quality: "green", weapon: "spear", kit: "gotland_levy", formation: "close", mounted: false };
const units = [
  unit("Gotland bowmen", GOT, 400, { ...LEVY, weapon: "bow", formation: "open" }, [20, 30, 30]),
  unit("Gotland levy", GOT, 1600, LEVY, [40, 20, 27]),
  unit("Gotland freeholders", GOT, 500, { ...LEVY, quality: "regular", weapon: "axe", kit: "gotland_armoured" }, [13, 34, 25]),
  unit("Danish crossbowmen", DAN, 500, { quality: "regular", weapon: "crossbow", kit: "transitional", formation: "open", mounted: false }, [25, 28, 52]),
  unit("Sergeants", DAN, 1000, { quality: "veteran", weapon: "spiked_club", kit: "transitional", formation: "close", mounted: false }, [25, 28, 55]),
  unit("Men-at-arms", DAN, 500, { quality: "veteran", weapon: "sword", kit: "danish_maa", formation: "close", mounted: false }, [13, 34, 57]),
];

writeField({
  id: "visby-1361", name: "Visby, 27 July 1361", sides: ["Gotlanders", "Danes"], table: "visby-1361-adjusted",
  travel: { map: "visby-1361", place: "Visby", within: 1, sides: ["Gotland", "Denmark"] },
  weather: "{cond: fair, wind: calm, ground: {mud: 0, snow: 0}}",
  grid, units, edgeWorks: { wall, gate },
  header: [
    `The battle outside Visby's walls, 27 July 1361 (Julian), at 10 m a hex: ${COLS} x ${ROWS} hexes, about`,
    "800 m east to west and 600 m north to south, north at the top.",
    "Generated by tools/maps/make_visby_field.mjs: edit that file and re-run it rather than this one.",
    "The wall, the south gate (barred), Solberga nunnery and the ground are drawn by hand to the",
    "accounts' description, not traced from any map; the deployment is our own reading, in our",
    "own words, with round numbers for play.",
    "",
    "What happened, briefly: the Gotland levies, beaten at Mästerby, met the Danish army again",
    "outside Visby's ring wall. The townsmen kept the gates shut and stayed out of it. The",
    "farmers, most in a padded coat and a mail hood at best, were no match for the Danes'",
    "professionals and hired Germans; their dead, many with crossbow bolts and blows to the legs",
    "and head, were buried in mass graves just outside the wall.",
  ],
});
console.log(grid.map(r => r.join("")).join("\n"));
